[project]
name = "dbttut"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-databricks>=1.10.15",
]
